#!/bin/bash

THREADS=${THREADS:-1}
COMPRESS=${COMPRESS:-yes}
MASTER2=${MASTER2:-$MASTER1}
ENV2=${ENV2:-$ENV1}

if [ -z $ENV1 ]; then
  echo "E: Must provide at least one environment"
  exit 1
fi

if [ -z $MASTER1 ]; then
  echo "E: Must provide at least one master"
  exit 1
fi

DATADIR="/reports"
mkdir -p $DATADIR

REPORT="${DATADIR}/${MASTER1}_${ENV1}_${MASTER2}_${ENV2}.json"

if [ -z $PUPPETDB ]; then
  USE_PUPPETDB="--use_puppetdb"
  PUPPETDB_PORT=${PUPPETDB_PORT:8081}
  cat <<EOF > /etc/puppetlabs/puppet/puppetdb.conf
[main]
port = $PUPPETDB_PORT
server = $PUPPETDB
soft_write_failure = false
EOF
fi

puppet catalog diff $MASTER1/$ENV1 $MASTER2/$ENV2 \
--show_resource_diff \
--content_diff \
--changed_depth 1000 \
--configtimeout 3000 \
--output_report $REPORT \
--debug $USE_PUPPETDB \
--threads $THREADS

if [ "x${COMPRESS}" = "xyes" ]; then
  gzip -c $REPORT > "${REPORT}.gz"
  REPORT="${REPORT} ${REPORT}.gz"
fi
