#!/bin/bash

THREADS=${THREADS:-1}
COMPRESS=${COMPRESS:-no}
MASTER1=${MASTER1:-puppet}
MASTER2=${MASTER2:-$MASTER1}
ENV1=${ENV1:-production}
ENV2=${ENV2:-$ENV1}

DATADIR="/data"
mkdir -p $DATADIR

DEFAULT_REPORT="${DATADIR}/${MASTER1}_${ENV1}_${MASTER2}_${ENV2}.json"
REPORT="${REPORT:-$DEFAULT_REPORT}"

if [ "x$USE_PUPPETDB" = "xyes" ]; then
  PUPPETDB_FLAG="--use_puppetdb"
  cat <<EOF > /etc/puppetlabs/puppet/puppetdb.conf
[main]
port = 8080
server = puppetdb
soft_write_failure = false
EOF
fi

puppet catalog diff $MASTER1/$ENV1 $MASTER2/$ENV2 \
--show_resource_diff \
--content_diff \
--changed_depth 1000 \
--configtimeout 3000 \
--output_report "${REPORT}" \
--debug $PUPPETDB_FLAG \
--threads $THREADS $@

if [ "x${COMPRESS}" = "xyes" ]; then
  gzip -c $REPORT > "${REPORT}.gz"
  REPORT="${REPORT}.gz"
fi

if [ "x${SYNC}" = "xyes" ]; then
  s3cmd put "${REPORT}" "s3://${S3_BUCKET}/${S3_DIR}/"
fi

/generate_reportlist.py
