#!/bin/bash

THREADS=${THREADS:-1}
COMPRESS=${COMPRESS:-yes}
MASTER2=${MASTER2:-$MASTER1}
ENV2=${ENV2:-$ENV1}

if [ -z $ENV1 ]; then
  echo "E: Must provide at least one environment"
  exit 1
fi

if [ -z $MASTER1 ]; then
  echo "E: Must provide at least one master"
  exit 1
fi

DATADIR="/reports"
mkdir -p $DATADIR

DEFAULT_REPORT="${DATADIR}/${MASTER1}_${ENV1}_${MASTER2}_${ENV2}.json"
REPORT=${REPORT:-$DEFAULT_REPORT}

if [ "x$USE_PUPPETDB" = "xyes" ]; then
  PUPPETDB_FLAG="--use_puppetdb"
  cat <<EOF > /etc/puppetlabs/puppet/puppetdb.conf
[main]
port = 8080
server = puppetdb
soft_write_failure = false
EOF
fi

puppet catalog diff $MASTER1/$ENV1 $MASTER2/$ENV2 \
--show_resource_diff \
--content_diff \
--changed_depth 1000 \
--configtimeout 3000 \
--output_report $REPORT \
--debug $PUPPETDB_FLAG \
--threads $THREADS

if [ "x${COMPRESS}" = "xyes" ]; then
  gzip -c $REPORT > "${REPORT}.gz"
  REPORT="${REPORT} ${REPORT}.gz"
fi
